### ISSUE TITLE
SDK is using reflection and causing crash on Android 14

### ISSUE THREAD

**Issue by seventhmoon** [tuya/tuya-home-android-sdk-sample-java#43]
A few apps using Tuya Home Android SDK is crashing on Android 14.

It is likely the SDK is trying to get [`android.location.Location.getMslAltitudeAccuracyMeters`](https://developer.android.com/reference/android/location/Location#getMslAltitudeAccuracyMeters()) by reflection, but it is not working in Android 14.

The following crash can be found in log.
```
com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.1.67
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:172)
        at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:14)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:36)
        at com.alibaba.fastjson.JSON.toJSONString(JSON.java:1)
        at pp4.c(LocationStorage.java:1)
        at rp4$c.b(TuyaLocationManager.java:4)
        at rp4$c.onSuccess(TuyaLocationManager.java:1)
        at com.tuya.smart.android.network.Business$RequestTask$3.run(Business.java:4)
        at android.os.Handler.handleCallback(Handler.java:958)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:205)
        at android.os.Looper.loop(Looper.java:294)
        at android.app.ActivityThread.main(ActivityThread.java:8174)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
Caused by: com.alibaba.fastjson.JSONException: write javaBean error, fastjson version 1.1.67, fieldName : location
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:172)
        at com.alibaba.fastjson.serializer.FieldSerializer.writeValue(FieldSerializer.java:25)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:154)
        ... 15 more
Caused by: com.alibaba.fastjson.JSONException: get property error。 android.location.Location.getMslAltitudeAccuracyMeters
        at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValue(FieldSerializer.java:4)
        at com.alibaba.fastjson.serializer.JavaBeanSerializer.write(JavaBeanSerializer.java:63)
        ... 17 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.alibaba.fastjson.util.FieldInfo.get(FieldInfo.java:3)
        at com.alibaba.fastjson.serializer.FieldSerializer.getPropertyValue(FieldSerializer.java:1)
        ... 18 more
Caused by: java.lang.IllegalStateException: The Mean Sea Level altitude accuracy of this location is not set.
        at com.android.internal.util.Preconditions.checkState(Preconditions.java:215)
        at android.location.Location.getMslAltitudeAccuracyMeters(Location.java:750)
        ... 21 more
 ```

**Comment by linhuiluo** [comment]
@seventhmoon Thanks for your feedback, the problem has been confirmed, we will adapt it for Android 14 in the near future, and will update the SDK again then.

**Comment by seventhmoon** [comment]
Android 14 SDK has been finalised, and this issue is affecting apps running on Android 14.

Is there any ETA for the fix?

**Comment by xionghai123** [comment]
> 

Thanks for the reminder, we are working on it and will post an update this week.

**Comment by xionghai123** [comment]
> Android 14 SDK has been finalised, and this issue is affecting apps running on Android 14.
> 
> Is there any ETA for the fix?

Thanks for the reminder, we are working on it and will post an update this week.

**Comment by seventhmoon** [comment]
Is the update released? 
The release notes seem not updated yet. 
https://developer.tuya.com/en/docs/app-development/changelog?id=Ka6o3br3pb4fo

**Comment by hossam-hani** [comment]
Is this problem solved?
