### ISSUE TITLE
Could not find a dependency

### ISSUE THREAD

**Issue by clopso** [tuya/tuya-home-android-sdk-sample-java#46]
### After the following steps:

1. [Create an app](https://developer.tuya.com/en/docs/app-development/preparation?id=Ka7mqlxh7vgi9)
2. [Config android studio project](https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj)

### This error happens:

```
   > Could not find com.thingclips.smart:thingsmart-ipc-camera-timeline:1.1.0.
     Searched in the following locations:
       - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-ipc-camera-timeline/1.1.0/thingsmart-ipc-camera-timeline-1.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-ipc-camera-timeline/1.1.0/thingsmart-ipc-camera-timeline-1.1.0.pom
       - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-ipc-camera-timeline/1.1.0/thingsmart-ipc-camera-timeline-1.1.0.pom
       - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-ipc-camera-timeline/1.1.0/thingsmart-ipc-camera-timeline-1.1.0.pom
     Required by:
         project :app > project :ipc
```

### This dependency was not found

https://github.com/tuya/tuya-home-android-sdk-sample-java/blob/e0e287a7128120107c9c19bf30503cc2b8a7403e/homesdk-sample/ipc/build.gradle#L49

**Comment by linhuiluo** [comment]
@clopso You can refer to this link : https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj#title-4-%E7%AC%AC%E4%BA%8C%E6%AD%A5%EF%BC%9A%E9%85%8D%E7%BD%AE%20build.gradle%20%E6%96%87%E4%BB%B6, In the root build.gradle file, add the { url 'https://maven-other.tuya.com/repository/maven-releases/' } in your project build.gradle .

**Comment by clopso** [comment]
Hey @linhuiluo, thanks for help!

When I put this url in "build.gradle" file, I can successfully build it!

But when running the app, a crash occurs with the following error:

```
FATAL EXCEPTION: main
    Process: app.demo.com, PID: 27311
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)
     at com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(Native Method)
     at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:58)
     at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
     at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
     at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:87)
     at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:255)
     at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:64)
     at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:272)
     at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:102)
     at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.java:33)
     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1212)
     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7095)
     at android.app.ActivityThread.access$1600(ActivityThread.java:269)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
     at android.os.Handler.dispatchMessage(Handler.java:106)
     at android.os.Looper.loopOnce(Looper.java:211)
     at android.os.Looper.loop(Looper.java:300)
     at android.app.ActivityThread.main(ActivityThread.java:8301)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1043)
```

**Comment by linhuiluo** [comment]
@clopso co  You can refer to this link : https://developer.tuya.com/cn/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-%E7%AC%AC%E4%B8%89%E6%AD%A5%EF%BC%9A%E9%9B%86%E6%88%90%E5%AE%89%E5%85%A8%E7%BB%84%E4%BB%B6 . It is worth noting that version 5.0 removes security images in your project .
