### ISSUE TITLE
Demo启动就崩溃

### ISSUE THREAD

**Issue by GGGGGGGGGGGGtu** [tuya/tuya-home-android-sdk-sample-java#49]
Process: com.test007.demo, PID: 29780
    java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)
        at com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(Native Method)
        at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:58)
        at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
        at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
        at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:87)
        at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:255)
        at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:64)
        at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:272)
        at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:102)
        at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.java:33)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7011)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2231)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8152)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

**Comment by GGGGGGGGGGGGtu** [comment]
沒有导入 security-algorithm-1.0.0-beta.aar
