### ISSUE TITLE
Could not find com.thingclips.smart:thingsmart-openssl-sdk:1.1.1t

### ISSUE THREAD

**Issue by code4a** [tuya/tuya-home-android-sdk-sample-java#50]
FAILURE: Build completed with 10 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.thingclips.smart:thingsmart-openssl-sdk:1.1.1t.
     Searched in the following locations:
       - https://maven-other.tuya.com/repository/maven-releases/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
       - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
       - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
       - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
       - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
     Required by:
         project :app > project :ipc > com.thingclips.smart:thingsmart-ipcsdk:5.1.0
   > Could not find com.thingclips.smart:thingsmart-modularCampAnno:1.0.0-SNAPSHOT.
     Searched in the following locations:
       - https://maven-other.tuya.com/repository/maven-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
       - https://maven-other.tuya.com/repository/maven-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
       - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
       - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
       - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
       - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
     Required by:
         project :app > project :base_res > com.thingclips.smart:thingsmart:5.1.0 > com.thingclips.smart:thingsmart-device-core:5.1.0 > com.thingclips.smart:thingsmart-asynclib:5.1.0-rc.3

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:mergeDebugResources'.
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:38)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1268)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$1800(DefaultConfiguration.java:142)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1245)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.visitContents(DefaultConfiguration.java:1238)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:266)
	at org.gradle.api.internal.file.CompositeFileCollection.visitContents(CompositeFileCollection.java:152)
	at org.gradle.api.internal.file.AbstractFileCollection.visitStructure(AbstractFileCollection.java:266)
	at org.gradle.internal.fingerprint.impl.DefaultFileCollectionSnapshotter.snapshot(DefaultFileCollectionSnapshotter.java:50)
	at org.gradle.internal.fingerprint.impl.AbstractFileCollectionFingerprinter.fingerprint(AbstractFileCollectionFingerprinter.java:47)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.lambda$visitInputFileProperties$1(ExecuteActionsTaskExecuter.java:326)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$fingerprintInputFiles$3(CaptureStateBeforeExecutionStep.java:192)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.visitInputFileProperties(ExecuteActionsTaskExecuter.java:324)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.fingerprintInputFiles(CaptureStateBeforeExecutionStep.java:188)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionState(CaptureStateBeforeExecutionStep.java:150)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$captureExecutionStateOp$1(CaptureStateBeforeExecutionStep.java:104)
	at org.gradle.internal.execution.steps.BuildOperationStep$1.call(BuildOperationStep.java:40)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.internal.execution.steps.BuildOperationStep.operation(BuildOperationStep.java:37)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.captureExecutionStateOp(CaptureStateBeforeExecutionStep.java:103)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.lambda$execute$0(CaptureStateBeforeExecutionStep.java:78)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:78)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:53)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:74)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.lambda$execute$2(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:78)
	at org.gradle.internal.execution.steps.SkipEmptyWorkStep.execute(SkipEmptyWorkStep.java:34)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:39)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:40)
	at org.gradle.internal.execution.steps.LoadExecutionStateStep.execute(LoadExecutionStateStep.java:28)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:194)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:186)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:409)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:399)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:242)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:150)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:94)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:356)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Cause 1: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.thingclips.smart:thingsmart-openssl-sdk:1.1.1t.
Searched in the following locations:
  - https://maven-other.tuya.com/repository/maven-releases/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
  - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
  - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
  - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
  - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-openssl-sdk/1.1.1t/thingsmart-openssl-sdk-1.1.1t.pom
Required by:
    project :app > project :ipc > com.thingclips.smart:thingsmart-ipcsdk:5.1.0
Cause 2: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.thingclips.smart:thingsmart-modularCampAnno:1.0.0-SNAPSHOT.
Searched in the following locations:
  - https://maven-other.tuya.com/repository/maven-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
  - https://maven-other.tuya.com/repository/maven-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
  - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
  - https://maven-other.tuya.com/repository/maven-commercial-releases/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
  - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
  - https://dl.google.com/dl/android/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
  - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
  - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/maven-metadata.xml
  - https://jcenter.bintray.com/com/thingclips/smart/thingsmart-modularCampAnno/1.0.0-SNAPSHOT/thingsmart-modularCampAnno-1.0.0-SNAPSHOT.pom
Required by:
    project :app > project :base_res > com.thingclips.smart:thingsmart:5.1.0 > com.thingclips.smart:thingsmart-device-core:5.1.0 > com.thingclips.smart:thingsmart-asynclib:5.1.0-rc.3

==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
125 actionable tasks: 125 executed

**Comment by linhuiluo** [comment]
@code4a Thank you for your feedback, we have located the problem, please re-synchronize the project, and then SNAPSHOT dependencies you can globally exclude, does not affect the use of the function Oh. Sorry again.We will update the sample later, thanks for your attention.
