### ISSUE TITLE
运行demo报错

### ISSUE THREAD

**Issue by RockVampire** [tuya/tuya-home-android-sdk-sample-java#52]
2023-07-26 16:53:23.501 14661-14661/com.test007.demo W/om.test007.dem: Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (unsupported, reflection, allowed)
2023-07-26 16:53:23.501 14661-14661/com.test007.demo W/om.test007.dem: Accessing hidden field Landroid/app/ActivityThread;->mInitialApplication:Landroid/app/Application; (unsupported, reflection, allowed)
2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libthing_security_algorithm.so" not found
2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err:     at java.lang.Runtime.loadLibrary0(Runtime.java:998)
2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err:     at java.lang.System.loadLibrary(System.java:1656)

**Comment by xionghai123** [comment]
> 2023-07-26 16:53:23.501 14661-14661/com.test007.demo W/om.test007.dem: Accessing hidden method Landroid/app/ActivityThread;->currentActivityThread()Landroid/app/ActivityThread; (unsupported, reflection, allowed) 2023-07-26 16:53:23.501 14661-14661/com.test007.demo W/om.test007.dem: Accessing hidden field Landroid/app/ActivityThread;->mInitialApplication:Landroid/app/Application; (unsupported, reflection, allowed) 2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: library "libthing_security_algorithm.so" not found 2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err: at java.lang.Runtime.loadLibrary0(Runtime.java:1077) 2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err: at java.lang.Runtime.loadLibrary0(Runtime.java:998) 2023-07-26 16:53:23.599 14661-14661/com.test007.demo W/System.err: at java.lang.System.loadLibrary(System.java:1656)

Please refer to the following documents to operate: https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj
