### ISSUE TITLE
dlopen failed: library "libthing_security_algorithm.so" not found

### ISSUE THREAD

**Issue by br3ant** [tuya/tuya-home-android-sdk-sample-java#53]
2023-08-17 21:45:26.357 27840-27840 System.err              com.test007.demo                     W  java.lang.UnsatisfiedLinkError: dlopen failed: library "libthing_security_algorithm.so" not found
2023-08-17 21:45:26.357 27840-27840 System.err              com.test007.demo                     W  	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at java.lang.System.loadLibrary(System.java:1656)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.security.jni.JNICLibrary.<clinit>(JNICLibrary.java:27)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:50)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:87)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:255)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:64)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:272)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:111)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.kt:37)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7094)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread.access$1600(ActivityThread.java:276)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2131)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.os.Looper.loopOnce(Looper.java:210)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.os.Looper.loop(Looper.java:299)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread.main(ActivityThread.java:8293)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at java.lang.reflect.Method.invoke(Native Method)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2023-08-17 21:45:26.358 27840-27840 System.err              com.test007.demo                     W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  java.lang.UnsatisfiedLinkError: dlopen failed: library "libthing_security_algorithm.so" not found
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at java.lang.Runtime.loadLibrary0(Runtime.java:998)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at java.lang.System.loadLibrary(System.java:1656)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.security.jni.JNICLibrary.<clinit>(JNICLibrary.java:27)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:50)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
2023-08-17 21:45:26.359 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:87)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:255)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:64)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:272)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:111)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.kt:37)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7094)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread.access$1600(ActivityThread.java:276)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2131)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.os.Handler.dispatchMessage(Handler.java:106)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.os.Looper.loopOnce(Looper.java:210)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.os.Looper.loop(Looper.java:299)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at android.app.ActivityThread.main(ActivityThread.java:8293)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at java.lang.reflect.Method.invoke(Native Method)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
2023-08-17 21:45:26.360 27840-27840 System.err              com.test007.demo                     W  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by taojingGino** [comment]
https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-Step%203%3A%20Integrate%20with%20security%20component

you can check this docment,looks like you haven't put security-algorithm.aar in the libs
