### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by mary-ng5519** [tuya/tuya-home-android-sdk-sample-java#57]
dear team, we love your work, current sourcebase get crashed error when launch app, please help check the source base configuration for below error
```
FATAL EXCEPTION: main
Process: com.test007.demo, PID: 1465
java.lang.UnsatisfiedLinkError: No implementation found for java.lang.Object com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(android.content.Context, int, byte[], byte[], boolean) (tried Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative and Java_com_thingclips_smart_security_jni_SecureNativeApi_doCommandNative__Landroid_content_Context_2I_3B_3BZ)
                                                                                                    	at com.thingclips.smart.security.jni.SecureNativeApi.doCommandNative(Native Method)
                                                                                                    	at com.thingclips.smart.security.jni.JNICLibrary.doCommandNative(JNICLibrary.java:58)
                                                                                                    	at com.thingclips.sdk.network.ThingNetworkSecurity.initJNI(ThingNetworkSecurity.java:9)
                                                                                                    	at com.thingclips.smart.android.network.ThingSmartNetWork.initialize(ThingSmartNetWork.java:35)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.initThingData(ThingSdk.java:87)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:255)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:64)
                                                                                                    	at com.thingclips.smart.sdk.ThingSdk.init(ThingSdk.java:272)
                                                                                                    	at com.thingclips.smart.home.sdk.ThingHomeSdk.init(ThingHomeSdk.java:111)
                                                                                                    	at com.tuya.appsdk.sample.BaseApplication.onCreate(BaseApplication.java:33)
                                                                                                    	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7593)
                                                                                                    	at android.app.ActivityThread.access$1500(ActivityThread.java:301)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2177)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8653)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
Tons of thanks

**Comment by taojingGino** [comment]
this error means you did not add security component
pls check this docs
@mary-ng5519 
https://developer.tuya.com/en/docs/app-development/integrated?id=Ka69nt96cw0uj#title-5-Step%203%3A%20Integrate%20with%20security%20component

**Comment by mary-ng5519** [comment]
@taojingGino 
dear, please help us below error build log, we renamed app package name so that it matches with tuya cloud backend dashboard settings
```
> Task :device_config:compileDebugJavaWithJavac FAILED
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:56: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:73: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:90: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:109: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:126: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:142: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:158: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\main\DeviceConfigFuncWidget.java:173: error: cannot find symbol
                            rootView.getContext().getString(R.string.home_current_home_tips),
                                                                    ^
  symbol:   variable home_current_home_tips
  location: class string
D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\zigbee\adapter\ZigBeeGatewayListAdapter.java:88: error: cannot find symbol
            holder.itemIcon.setImageResource(R.drawable.ic_check);
                                              ^
  symbol:   variable drawable
  location: class R
Note: D:\tuya-home-android-sdk-sample-java-main\homesdk-sample\device_config\src\main\java\com\tuya\appsdk\sample\device\config\zigbee\adapter\ZigBeeGatewayListAdapter.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
9 errors
```

**Comment by taojingGino** [comment]
@mary-ng5519 
Could you please check if you have changed the dependencies and check if these two resources exist in the demo project? We try to run the demo ourselves again, and it is works okay.
